/**
 * Mock enforcement reports for the Enforcer Dashboard.
 * In production these stream in over WebSocket from the MMDA backend.
 */

export const MOCK_REPORTS = [
  {
    id: 'r001',
    plateNumber: 'ABC 1234',
    violationType: 'Double Parking',
    latitude: 14.5876,
    longitude: 121.0607,
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    photoUrl: null,
    aiVerified: true,
    confidence: 0.92,
    address: 'Julia Vargas Ave, Ortigas Center, Pasig',
    status: 'pending',
  },
  {
    id: 'r002',
    plateNumber: 'XYZ 5678',
    violationType: 'Blocking Driveway',
    latitude: 14.5643,
    longitude: 121.0019,
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    photoUrl: null,
    aiVerified: true,
    confidence: 0.88,
    address: 'EDSA cor. Taft Ave, Pasay',
    status: 'pending',
  },
  {
    id: 'r003',
    plateNumber: 'MNL 9012',
    violationType: 'No Parking Zone',
    latitude: 14.5975,
    longitude: 120.9839,
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    photoUrl: null,
    aiVerified: false,
    confidence: 0.71,
    address: 'Quezon Blvd, Quiapo, Manila',
    status: 'pending',
  },
  {
    id: 'r004',
    plateNumber: 'QCY 3456',
    violationType: 'Sidewalk Parking',
    latitude: 14.5547,
    longitude: 121.0244,
    timestamp: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    photoUrl: null,
    aiVerified: false,
    confidence: 0.65,
    address: 'Ayala Ave, Makati CBD',
    status: 'pending',
  },
  {
    id: 'r005',
    plateNumber: 'MMD 7890',
    violationType: 'Blocking Intersection',
    latitude: 14.5512,
    longitude: 121.0494,
    timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    photoUrl: null,
    aiVerified: true,
    confidence: 0.95,
    address: '5th Ave cor. 32nd St, BGC, Taguig',
    status: 'dispatched',
  },
];
